data:
  num_nodes: 307
  in_steps: 12
  out_steps: 12
  val_ratio: 0.2
  test_ratio: 0.2
  normalizer: std

model:
  input_dim: 5
  flow_dim: 1
  period_dim: 1
  weekend_dim: 1
  holiday_dim: 1
  hop_dim: 1
  weather_dim: 0

  dim_embed_feature: 120
  input_embedding_dim: 80
  periods_embedding_dim: [24]
  weekend_embedding_dim: 6
  holiday_embedding_dim: 2
  spatial_embedding_dim: 0
  adaptive_embedding_dim: 8

  output_dim: 1
  embed_dim: 6
  rnn_units: 64
  num_layers: 3
  periods: [288,144,96,154,155,333,1888,2124,72,339]

  predict_time: 2
  gat_hidden: 256
  mlp_hidden: 256
train:
  loss_func: mae
  random: False
  seed: 10
  batch_size: 64
  epochs: 120
  lr_init: 0.006
  lr_decay: True
  lr_decay_rate: 0.2
  lr_decay_step: 80,100
  early_stop: True
  early_stop_patience: 15
  grad_norm: False
  max_grad_norm: 5
  real_value: True

test:
  mae_thresh: None
  mape_thresh: 0.

log:
  log_dir: 
  log_step: 20
  plot: False
