data:
  num_nodes: 883
  in_steps: 12
  out_steps: 12
  val_ratio: 0.2
  test_ratio: 0.2
  normalizer: std
  adj_norm: False
model:
  input_dim: 5
  flow_dim: 1
  period_dim: 1
  weekend_dim: 1
  holiday_dim: 1
  hop_dim: 1
  weather_dim: 0
  dim_discriminator: 128
  alpha_discriminator: 0.2

  dim_embed_feature: 60
  input_embedding_dim: 32
  periods_embedding_dim: [12]
  weekend_embedding_dim: 6
  holiday_embedding_dim: 2
  spatial_embedding_dim: 0
  adaptive_embedding_dim: 8

  output_dim: 1
  embed_dim: 16
  rnn_units: 32
  num_layers: 3
  periods: [144,288,96,155,336,134,252,2016,72,168]

  predict_time: 3
  gat_hidden: 128
  mlp_hidden: 128
  gat_drop: 0.6
  gat_heads: 1
  gat_alpha: 0.2
  gat_concat: True
  mlp_act: 'gelu'
  mlp_drop: .0
  num_gat: 0
  num_back: 0
train:
  loss_func: mae
  random: False
  seed: 10
  batch_size: 64
  epochs: 100
  lr_init: 0.006
  lr_decay: True
  lr_decay_rate: 0.3
  lr_decay_step: 25,45,75
  early_stop: True
  early_stop_patience: 15
  grad_norm: False
  max_grad_norm: 5
  real_value: True

test:
  mae_thresh: None
  mape_thresh: 0.

log:
  log_dir: 
  log_step: 20
  plot: False
